name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: create-env-json
        uses: schdck/create-env-json@v2
        with:
          file-name: "env.json"
          MNEMONIC: ${{ secrets.MNEMONIC }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
      - run: npm install
      - run: npm test
